spring:
  profiles:
    active: dev
  application:
    name: 'order-service-api'
  config:
    import: 'configserver:'

#spring:
#  application:
#    name: 'order-service-api'
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/helpdesk
#    username: postgres
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true
#
#springdoc:
#  openapi:
#    info:
#      title: 'Order Service API'
#      description: 'This is a order service API'
#      version: '1.0.0'
#
#server:
#  port: ${SERVER_PORT:8100}
