spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: 'https://github.com/fariasmk/Help-Desk-Server-Configs'
          username: 'fariasmk'
          password: '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'
server:
  port: ${PORT:8888}