spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: 'https://github.com/fariasmk/Help-Desk-Server-Configs'
          username: 'fariasmk'
          password: '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'
server:
  port: ${PORT:8888}